config/routes.rb
Rails.application.routes.draw do
  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'players#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord

  # this is how we map from the key values in json to attribute names in our model.
  JSON_TO_ATTRIBUTE_MAP = {
    "Player" => "name",
    "Team" => "team",
    "Pos" => "position",
    "Att/G" => "rushing_per_game_average",
    "Att" => "rushing_attempts",
    "Yds" => "total_rushing_yards",
    "Avg" =>  "rushing_average_yards_per_attempt",
    "Yds/G" => "rushing_yards_per_game",
    "TD" => "total_rushing_touchdowns",
    "Lng" => "longest_rush",
    "1st" => "rushing_first_downs",
    "1st%" => "rushing_first_downs_percentage",
    "20+" =>  "rushing_20_yards",
    "40+" => "rushing_40_yards",
    "FUM" => "fumbles",
  }

  # a helper to convert json record into an ActiveRecord
  def self.from_json(json = nil)
    raise if json == nil
    player = Player.new
    JSON_TO_ATTRIBUTE_MAP.each { |json_attr, model_key| player.update_attribute(model_key, json[json_attr]) }
    player
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
require 'csv'
class PlayersController < ApplicationController

  # main entry method into the player table
  def index
    @grid = PlayersGrid.new(grid_params) do |scope|
      scope.page(params[:page])
    end


    respond_to do |format|
      # for html we just return the default handler
      format.html
      # for csv we build based on current view
      format.csv {
        send_data to_cvs(@grid.assets),
          filename: "export.csv",
          type: 'text/csv; charset=utf-8' 
    }
    end
  end
  
  protected

  def grid_params
    params.fetch(:players_grid, {}).permit!
  end

  # convert active recrod to csv
  def to_cvs(assets)
    csv_string = CSV.generate do |csv|
      csv << Player.attribute_names
      assets.each do |player|
        csv << player.attributes.values
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nflrushing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<%= datagrid_form_for @grid, :method => :get, :url => players_path %>
<%= paginate(@grid.assets) %>
<%= datagrid_table @grid %>
<%= paginate(@grid.assets) %>
<a href="/players.csv?<%= params.permit!.to_query %>">Export current view </a>